# Generated by Django 4.2.3 on 2023-07-21 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_room_roomnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='roomCode',
            field=models.UUIDField(default=uuid.uuid1, unique=True),
        ),
        migrations.AlterField(
            model_name='roomnumber',
            name='usersConnected',
            field=models.IntegerField(default=0),
        ),
    ]
