# Generated by Django 4.2.3 on 2023-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_roomnumber_roomcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomnumber',
            name='roomCode',
            field=models.IntegerField(blank=True),
        ),
    ]
